version: '3.8'

services:
  fogis-auth-monitor:
    image: alpine:latest
    container_name: fogis-auth-monitor
    restart: unless-stopped
    depends_on:
      - fogis-api-client-service
    environment:
      - FOGIS_API_URL=http://fogis-api-client-service:8080
      - CHECK_INTERVAL=300  # 5 minutes - reduced frequency
      - MAX_FAILURES=2      # Lower threshold since we have loud alerting
      - LOG_FILE=/var/log/fogis-auth-monitor.log
      # Optional: Add webhook URL for alerts
      # - ALERT_WEBHOOK=https://your-webhook-url.com/alerts
    volumes:
      - ./scripts/monitor-fogis-auth.sh:/usr/local/bin/monitor-fogis-auth.sh:ro
      - ./logs/monitoring:/var/log
    command: |
      sh -c "
        apk add --no-cache curl jq bash &&
        chmod +x /usr/local/bin/monitor-fogis-auth.sh &&
        /usr/local/bin/monitor-fogis-auth.sh monitor
      "
    networks:
      - fogis-network
    healthcheck:
      test: ["CMD", "/usr/local/bin/monitor-fogis-auth.sh", "check"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s

networks:
  fogis-network:
    external: true
