# FOGIS Deployment Master Configuration Template
# Version: 2.0
#
# This is the portable configuration template for FOGIS deployment.
# Copy this file to 'fogis-config.yaml' and customize the values below.
#
# For detailed setup instructions, see: README.md
# For migration from legacy configuration, run: ./manage_fogis_system.sh config-migrate

# Configuration metadata
metadata:
  version: "2.0"
  created: ""  # Will be auto-filled when configuration is generated
  description: "FOGIS Complete System Configuration"

# FOGIS Authentication (REQUIRED)
# These credentials are used to authenticate with the FOGIS system
fogis:
  username: ""           # Your FOGIS login username (e.g., "Bartek Svaberg")
  password: ""           # Your FOGIS login password
  referee_number: 0      # Your referee number from FOGIS profile (e.g., 61318)

# Google Integration Configuration (REQUIRED)
google:
  # OAuth Configuration
  # You must create a Google Cloud Project and OAuth credentials
  # See: docs/OAUTH_SETUP_CHECKLIST.md for detailed instructions
  oauth:
    client_type: "web_application"  # Must be "web_application" for proper setup
    scopes:
      - "https://www.googleapis.com/auth/calendar"
      - "https://www.googleapis.com/auth/contacts"
      - "https://www.googleapis.com/auth/drive"

  # Google Calendar Configuration
  calendar:
    calendar_id: "primary"              # Use "primary" for main calendar, or specific calendar ID
    sync_tag: "FOGIS_CALENDAR_SYNC"     # Tag used to identify FOGIS events
    days_to_keep_past_events: 7         # How many days to keep past events

  # Google Drive Configuration
  drive:
    folder_base: "WhatsApp_Group_Assets"  # Base folder name for uploads
    auto_create_folders: true             # Automatically create folders if they don't exist

# Service Configuration
services:
  # Port mappings for external access
  # These ports are used to access services from outside the Docker network
  ports:
    api_client: 9086              # FOGIS API Client service
    match_processor: 9082         # Match List Processor service
    calendar_sync: 9083           # Calendar Sync service (main)
    calendar_auth: 9084           # Calendar Auth service (OAuth)
    calendar_web_trigger: 9087    # Calendar Web Trigger service
    logo_combiner: 9088           # Team Logo Combiner service
    google_drive: 9085            # Google Drive service
    change_detector: 9080         # Match List Change Detector service

  # Processing settings
  processing:
    min_referees_for_whatsapp: 2        # Minimum referees required for WhatsApp group creation
    match_check_schedule: "0 * * * *"   # Cron schedule for match checking (hourly)
    force_fresh_processing: true        # Force fresh processing on startup
    service_interval: 300               # Service check interval in seconds

  # Logging configuration
  logging:
    level: "INFO"           # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
    debug_mode: false       # Enable debug mode for development
    verbose_logging: false  # Enable verbose logging for troubleshooting

# System Configuration
system:
  # Docker configuration
  docker:
    restart_policy: "unless-stopped"  # Docker restart policy
    network_name: "fogis-network"     # Docker network name
    use_ghcr_images: true             # Use pre-built images from GitHub Container Registry

  # Directory paths (container-relative)
  paths:
    data: "/app/data"           # Data directory inside containers
    logs: "/app/logs"           # Logs directory inside containers
    credentials: "/app/credentials"  # Credentials directory inside containers
    temp: "/tmp"                # Temporary directory inside containers

  # Health check configuration
  health:
    interval: 30      # Health check interval in seconds
    timeout: 10       # Health check timeout in seconds
    retries: 3        # Number of health check retries
    start_period: 40  # Grace period before health checks start

# Notification Configuration (Optional)
# Configure notifications for system events and alerts
notifications:
  # Email notifications
  email:
    enabled: false                    # Enable email notifications
    sender: ""                        # Sender email address
    receiver: ""                      # Receiver email address
    smtp_server: "smtp.gmail.com"     # SMTP server
    smtp_port: 587                    # SMTP port

  # Discord notifications
  discord:
    enabled: false      # Enable Discord notifications
    webhook_url: ""     # Discord webhook URL

  # Slack notifications
  slack:
    enabled: false      # Enable Slack notifications
    webhook_url: ""     # Slack webhook URL

# Backup Configuration
backup:
  enabled: true                    # Enable automatic backups
  retention_days: 30               # How many days to keep backups
  include_logs: false              # Include logs in backups
  include_processing_state: false  # Include processing state (set to false for clean installations)