service:
  # The URL of this service
  publicurl: http://localhost:3456
  
  # Whether to allow user registration
  enableregistration: false
  
  # Whether to enable email reminders for tasks
  enableemailreminders: false
  
  # Whether to enable task attachments
  enabletaskattachments: true
  
  # The time zone all timestamps are in
  timezone: UTC
  
  # Whether to enable public teams (disabled for family privacy)
  enablepublicteams: false
  
  # JWT secret for authentication (CHANGE THIS!)
  jwtsecret: your-jwt-secret-change-this-to-something-secure

database:
  # Database type
  type: sqlite
  # Database file path for SQLite
  path: /app/vikunja/db/vikunja.db

mailer:
  # Whether to enable the mailer or not
  enabled: false

files:
  # The maximum size of a file, as a human-readable string.
  maxsize: 20MB

ratelimit:
  # whether or not to enable the rate limit
  enabled: true
  # The kind on which rates are based. Can be either "user" for a rate limit per user or "ip" for an ip-based rate limit.
  kind: user
  # The time limit for the rate limit
  limit: 100
  # The time period in seconds for the rate limit
  period: 60

log:
  # A numeric value which configures the log level
  level: INFO
  # Whether to log database queries or not
  database: off

# Authentication configuration
auth:
  # Local authentication
  local:
    # Whether to enable local authentication
    enabled: true
  
  # OpenID configuration (for future Google SSO if needed)
  openid:
    # Whether to enable OpenID Connect authentication
    enabled: false
    # Uncomment and configure these if you want to add Google SSO later:
    # redirecturl: http://localhost:3456/auth/openid/google/callback
    # providers:
    #   - name: google
    #     authurl: https://accounts.google.com/o/oauth2/v2/auth
    #     logouturl: https://accounts.google.com/logout
    #     tokenurl: https://oauth2.googleapis.com/token
    #     userinfourl: https://openidconnect.googleapis.com/v1/userinfo
    #     clientid: your-google-client-id
    #     clientsecret: your-google-client-secret
