# FOGIS Deployment - OAuth Tokens Secret
apiVersion: v1
kind: Secret
metadata:
  name: fogis-oauth-tokens
  namespace: fogis
  labels:
    app: fogis-deployment
type: Opaque
data:
  # Base64 encoded OAuth tokens (will be populated by init containers)
  CALENDAR_TOKEN: ""
  DRIVE_TOKEN: ""
  CONTACTS_TOKEN: ""
