# FOGIS Deployment - Kubernetes Secrets
# Note: Replace base64 encoded values with your actual credentials
apiVersion: v1
kind: Secret
metadata:
  name: fogis-secrets
  namespace: fogis
  labels:
    app: fogis-deployment
type: Opaque
data:
  # Base64 encoded FOGIS password
  FOGIS_PASSWORD: ""  # echo -n "your-password" | base64

  # Base64 encoded Google OAuth credentials
  GOOGLE_CREDENTIALS: ""  # base64 < credentials.json
