version: '3.8'

services:
  fogis-calendar-phonebook-sync:
    image: ghcr.io/pitchconnect/fogis-calendar-phonebook-sync:latest
    container_name: fogis-calendar-phonebook-sync-prod
    restart: unless-stopped
    ports:
      - "9089:5003"  # Main application port (app runs on 5003 inside container)
      - "9090:8080"  # OAuth authorization server port
    environment:
      # OAuth Credential Path Configuration (NEW FIXES)
      - TOKEN_PATH=/app/credentials/tokens/calendar/token.json
      - GOOGLE_CREDENTIALS_PATH=/app/credentials/google-credentials.json
      - GOOGLE_CALENDAR_TOKEN_FILE=/app/credentials/tokens/calendar/token.json

      # Service Configuration
      - PORT=9082
      - AUTH_SERVER_PORT=9083
      - AUTH_SERVER_HOST=localhost

      # FOGIS API Configuration
      - FOGIS_USERNAME=${FOGIS_USERNAME:-}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD:-}

      # Logging Configuration
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1

    volumes:
      # OAuth Credentials and Tokens
      - ./credentials:/app/credentials:rw
      - ./data:/app/data:rw

      # Configuration
      - ./config.json:/app/config.json:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - fogis-network

networks:
  fogis-network:
    driver: bridge
